yaseenkadir/etchedjournal

backend/build.gradle
Upgraded Spring Boot version from 1.5.9 to 1.5.13.
Also explicitly defining versions for other dependencies.
=> #7: Upgraded Spring Boot version

frontend-ng/src/app/etches/editor/entry-title/entry-title.component.html, frontend-ng/src/app/etches/editor/entry-title/entry-title.component.spec.ts, frontend-ng/src/app/etches/editor/entry-title/entry-title.component.ts, frontend-ng/src/styles.css
=> Fixed title input not in focus when editing

frontend-ng/src/app/app.component.spec.ts, frontend-ng/src/app/app.component.ts, frontend-ng/src/app/app.module.ts
=> Updated html title in frontend app

frontend-ng/src/app/app.module.ts, frontend-ng/src/app/directives/app-auto-focus.directive.spec.ts, frontend-ng/src/app/directives/app-auto-focus.directive.ts, frontend-ng/src/app/etches/editor/entry-editor/entry-editor.component.html, frontend-ng/src/app/etches/editor/entry-editor/entry-editor.component.ts, frontend-ng/src/app/etches/editor/entry-title/entry-title.component.html, frontend-ng/src/app/etches/editor/entry-title/entry-title.component.spec.ts, frontend-ng/src/app/etches/editor/entry-title/entry-title.component.ts, frontend-ng/src/app/user/configure-passphrase/configure-passphrase.component.html, frontend-ng/src/app/user/login/login.component.html, frontend-ng/src/app/user/passphrase/enter-passphrase/enter-passphrase.component.html, frontend-ng/src/app/user/register/register.component.html
=> Autofocusing when input elements come into view

frontend-ng/src/app/app-routing-utils.ts, frontend-ng/src/app/app-routing.module.spec.ts, frontend-ng/src/app/app-routing.module.ts, frontend-ng/src/app/auth/auth.guard.spec.ts, frontend-ng/src/app/auth/auth.guard.ts
Redirecting to the login page when a user requests a page that requires auth AND they are not logged in.
=> Redirecting to login page for routes that require auth

frontend-ng/package-lock.json, frontend-ng/package.json, frontend-ng/src/app/app-routing-utils.ts, frontend-ng/src/app/app-routing.module.spec.ts, frontend-ng/src/app/app-routing.module.ts, frontend-ng/src/app/app.module.ts, frontend-ng/src/app/auth/auth.interceptor.spec.ts, frontend-ng/src/app/auth/auth.interceptor.ts, frontend-ng/src/app/services/encrypter.service.ts, frontend-ng/src/app/services/etched-api.service.spec.ts, frontend-ng/src/app/services/etched-api.service.ts, frontend-ng/src/app/user/login/login-container/login-container.component.html, frontend-ng/src/app/user/login/login-container/login-container.component.spec.ts, frontend-ng/src/app/user/login/login-container/login-container.component.ts, frontend-ng/src/app/user/passphrase/enter-passphrase/enter-passphrase-container/enter-passphrase-container.component.html, frontend-ng/src/app/user/passphrase/enter-passphrase/enter-passphrase-container/enter-passphrase-container.component.spec.ts, frontend-ng/src/app/user/passphrase/enter-passphrase/enter-passphrase-container/enter-passphrase-container.component.ts, frontend-ng/src/app/user/passphrase/passphrase.guard.spec.ts, frontend-ng/src/app/user/passphrase/passphrase.guard.ts, frontend-ng/src/app/utils/token-decoder.ts
=> Persisting session/login details on frontend

frontend-ng/src/app/services/auth.service.spec.ts, frontend-ng/src/app/services/auth.service.ts, frontend-ng/src/app/user/login/login-container/login-container.component.html, frontend-ng/src/app/user/login/login-container/login-container.component.spec.ts, frontend-ng/src/app/user/login/login-container/login-container.component.ts, frontend-ng/src/app/user/login/login.component.html, frontend-ng/src/app/user/login/login.component.spec.ts, frontend-ng/src/app/user/login/login.component.ts
=> Handling invalid password errors and username not exist erros

frontend-ng/src/app/services/auth.service.spec.ts, frontend-ng/src/app/services/auth.service.ts, frontend-ng/src/app/user/register/register-container/register-container.component.html, frontend-ng/src/app/user/register/register-container/register-container.component.spec.ts, frontend-ng/src/app/user/register/register-container/register-container.component.ts, frontend-ng/src/app/user/register/register.component.html, frontend-ng/src/app/user/register/register.component.spec.ts, frontend-ng/src/app/user/register/register.component.ts
=> Handling username already taken

backend/src/main/kotlin/com/etchedjournal/etched/security/CognitoConfiguration.kt, backend/src/main/resources/application-dev.yml, backend/src/main/resources/application.yml, backend/src/test/resources/application.properties, deploy/cognito.yml, deploy/deployer.py, deploy/test_deployer.py, frontend-ng/src/environments/environment.ts
=> Automated deployment of authentication

frontend-ng/src/app/app.component.html, frontend-ng/src/app/app.component.spec.ts, frontend-ng/src/app/app.component.ts, frontend-ng/src/app/app.module.ts, frontend-ng/src/app/nav/nav.component.css, frontend-ng/src/app/nav/nav.component.html, frontend-ng/src/app/nav/nav.component.spec.ts, frontend-ng/src/app/nav/nav.component.ts, frontend-ng/src/app/services/auth.service.spec.ts, frontend-ng/src/app/services/auth.service.ts
=> Added logout functionality

frontend-ng/src/app/etches/editor/entry-title/entry-title.component.html, frontend-ng/src/app/etches/editor/entry-title/entry-title.component.ts
=> Pressing enter updates entry title

frontend-ng/src/app/app-routing-utils.ts, frontend-ng/src/app/app-routing.module.spec.ts, frontend-ng/src/app/app-routing.module.ts, frontend-ng/src/app/app.module.ts, frontend-ng/src/app/key-pairs/generate/generate-container.component.html, frontend-ng/src/app/key-pairs/generate/generate-container.component.spec.ts, frontend-ng/src/app/key-pairs/generate/generate-container.component.ts, frontend-ng/src/app/user/passphrase/enter-passphrase/enter-passphrase-container/enter-passphrase-container.component.spec.ts, frontend-ng/src/app/user/passphrase/enter-passphrase/enter-passphrase-container/enter-passphrase-container.component.ts, frontend-ng/src/app/user/register/register-container/register-container.component.html, frontend-ng/src/app/user/register/register-container/register-container.component.spec.ts, frontend-ng/src/app/user/register/register-container/register-container.component.ts
=> Redirecting to keys generation when no keys are configured

frontend-ng/src/app/app.component.spec.ts, frontend-ng/src/app/app.module.ts, frontend-ng/src/app/etches/editor/editor-container.component.spec.ts, frontend-ng/src/app/etches/editor/entry-editor/entry-editor.component.html, frontend-ng/src/app/etches/editor/entry-editor/entry-editor.component.spec.ts, frontend-ng/src/app/etches/editor/etch-item/etch-item.component.css, frontend-ng/src/app/etches/editor/etch-item/etch-item.component.html, frontend-ng/src/app/etches/editor/etch-item/etch-item.component.spec.ts, frontend-ng/src/app/etches/editor/etch-item/etch-item.component.ts, frontend-ng/src/app/etches/editor/existing-entry-editor-container/existing-entry-editor-container.component.spec.ts
- Added new component to display individual etches
- Can be expanded to display the timestamp of the etch
=> GH-83 Displaying timestamps of etches

frontend-ng/src/app/etches/journals/create-journal/create-journal.component.css, frontend-ng/src/app/etches/journals/create-journal/create-journal.component.html
=> GH-85 Explaining how journals work on create page

frontend-ng/angular.json, frontend-ng/extra-webpack.config.js, frontend-ng/package-lock.json, frontend-ng/package.json, frontend-ng/src/app/services/encrypter.spec.ts, frontend-ng/src/app/services/encrypter.ts, frontend-ng/src/assets/openpgp.min.js, frontend-ng/src/assets/openpgp.worker.min.js, frontend-ng/src/environments/environment.prod.ts, frontend-ng/src/environments/environment.ts, frontend-ng/src/index.html
Fixes GH-89.
- Hosting openpgp.min.js and openpgp.worker.min.js under `/assets/`
- Excluding openpgp from webpack bundle
=> GH-89 Using web workers with openpgp

frontend-ng/package-lock.json, frontend-ng/package.json
=> GH-91 Upgraded openpgpjs to 4.4.5

README.md, backend/build.gradle, backend/src/main/resources/application.yml, backend/src/main/resources/db/migration/postgresql/V1_0__schema.sql, backend/src/test/resources/application.properties, docker-compose.yml
Fixes GH-88.
Using postgres as the backend persistent data store.
=> GH-88 Use persistent db

frontend-ng/src/app/services/location.service.spec.ts, frontend-ng/src/app/services/location.service.ts, frontend-ng/src/app/user/logout/logout.component.spec.ts, frontend-ng/src/app/user/logout/logout.component.ts
=> GH-82 Reloading page on logout

frontend-ng/package-lock.json, frontend-ng/package.json, frontend-ng/src/app/app.component.spec.ts, frontend-ng/src/app/app.module.ts, frontend-ng/src/app/etches/entry-list/entry-list-container.component.ts, frontend-ng/src/app/etches/journals/create-journal/create-journal.component.spec.ts, frontend-ng/src/app/etches/journals/create-journal/create-journal.component.ts, frontend-ng/src/app/etches/journals/journals-container/journals-container.component.html, frontend-ng/src/app/etches/journals/journals-container/journals-container.component.spec.ts, frontend-ng/src/app/etches/journals/journals-container/journals-container.component.ts, frontend-ng/src/app/nav/nav.component.html, frontend-ng/src/app/nav/nav.component.spec.ts, frontend-ng/src/app/nav/nav.component.ts, frontend-ng/src/app/services/encrypter.ts, frontend-ng/src/app/stores/journal.store.spec.ts, frontend-ng/src/app/stores/journal.store.ts
=> Display journals in navbar

frontend-ng/src/app/etches/journals/journals-container/journals-container.component.spec.ts, frontend-ng/src/app/etches/journals/journals-container/journals-container.component.ts, frontend-ng/src/app/services/encrypter.service.spec.ts, frontend-ng/src/app/services/encrypter.service.ts, frontend-ng/src/app/stores/journal.store.spec.ts, frontend-ng/src/app/stores/journal.store.ts
=> GH-105 navbar not populated

.travis.yml
=> GH-113 Enabling caching

frontend-ng/src/app/etches/editor/editor-container.component.html, frontend-ng/src/app/etches/editor/editor-container.component.spec.ts, frontend-ng/src/app/etches/editor/editor-container.component.ts, frontend-ng/src/app/etches/editor/entry-title/entry-title.component.spec.ts, frontend-ng/src/app/etches/editor/entry-title/entry-title.component.ts, frontend-ng/src/app/etches/editor/existing-entry-editor-container/existing-entry-editor-container.component.html, frontend-ng/src/app/etches/editor/existing-entry-editor-container/existing-entry-editor-container.component.spec.ts, frontend-ng/src/app/etches/editor/existing-entry-editor-container/existing-entry-editor-container.component.ts, frontend-ng/src/app/stores/entry.store.spec.ts, frontend-ng/src/app/stores/entry.store.ts
Forgot to migrate some components.
=> GH-117 Migrated other components to use entry store

frontend-ng/src/app/app.module.ts, frontend-ng/src/app/etches/editor/editor-container.component.spec.ts, frontend-ng/src/app/etches/editor/existing-entry-editor-container/existing-entry-editor-container.component.html, frontend-ng/src/app/etches/editor/existing-entry-editor-container/existing-entry-editor-container.component.spec.ts, frontend-ng/src/app/etches/editor/existing-entry-editor-container/existing-entry-editor-container.component.ts, frontend-ng/src/app/services/etch-queue.service.spec.ts, frontend-ng/src/app/services/etch-queue.service.ts, frontend-ng/src/app/stores/etch.store.spec.ts, frontend-ng/src/app/stores/etch.store.ts
=> GH-118 Migrated etches to use a mobx store

frontend-ng/src/app/user/configure-passphrase/configure-passphrase.component.spec.ts, frontend-ng/src/app/user/form-utils.ts
=> GH-119 Reduced minimum passphrase length to 10

backend/build.gradle, backend/src/main/kotlin/com/etchedjournal/etched/dto/EncryptionPropertiesRequest.kt, backend/src/main/kotlin/com/etchedjournal/etched/dto/RegisterResponse.kt, backend/src/main/kotlin/com/etchedjournal/etched/security/ExceptionHandledFilter.kt, backend/src/main/kotlin/com/etchedjournal/etched/security/NonLocalConfig.kt, backend/src/main/kotlin/com/etchedjournal/etched/security/WebSecurityConfig.kt, backend/src/test/kotlin/com/etchedjournal/etched/TestConfig.kt, backend/src/test/kotlin/com/etchedjournal/etched/security/CognitoAuthenticationMapperTest.kt, build.sh
=> GH-126 Using ktlint for backend code style checks

backend/src/main/kotlin/com/etchedjournal/etched/repository/JournalRepository.kt, backend/src/main/kotlin/com/etchedjournal/etched/service/impl/JournalServiceImpl.kt, backend/src/test/kotlin/com/etchedjournal/etched/TestConfig.kt, backend/src/test/kotlin/com/etchedjournal/etched/TestRepoUtils.kt, backend/src/test/kotlin/com/etchedjournal/etched/controller/JournalServiceControllerTests.kt, backend/src/test/kotlin/com/etchedjournal/etched/repository/JournalRepositoryTest.kt
Ordered by id which represents time ascending ordering.
Fixes #129.
=> GH-129 Ordering journal responses

backend/src/main/kotlin/com/etchedjournal/etched/repository/EntryRepository.kt, backend/src/main/kotlin/com/etchedjournal/etched/service/impl/EntryServiceImpl.kt, backend/src/test/kotlin/com/etchedjournal/etched/TestConfig.kt, backend/src/test/kotlin/com/etchedjournal/etched/TestRepoUtils.kt, backend/src/test/kotlin/com/etchedjournal/etched/repository/EntryRepositoryTest.kt
=> GH-130 Entries are ordered

backend/src/main/kotlin/com/etchedjournal/etched/repository/EtchRepository.kt, backend/src/main/kotlin/com/etchedjournal/etched/service/impl/EtchServiceImpl.kt, backend/src/test/kotlin/com/etchedjournal/etched/TestConfig.kt, backend/src/test/kotlin/com/etchedjournal/etched/TestRepoUtils.kt, backend/src/test/kotlin/com/etchedjournal/etched/repository/EtchRepositoryTest.kt
=> GH-131 Etch responses are ordered

backend/src/main/kotlin/com/etchedjournal/etched/repository/KeyPairRepository.kt, backend/src/main/kotlin/com/etchedjournal/etched/service/impl/KeypairServiceImpl.kt, backend/src/test/kotlin/com/etchedjournal/etched/TestConfig.kt, backend/src/test/kotlin/com/etchedjournal/etched/TestRepoUtils.kt, backend/src/test/kotlin/com/etchedjournal/etched/repository/KeyPairRepositoryTest.kt
=> GH-132 KeyPair responses are ordered

backend/build.gradle, backend/src/main/kotlin/com/etchedjournal/etched/controller/ExceptionAdvice.kt, backend/src/main/kotlin/com/etchedjournal/etched/service/impl/AuthServiceImpl.kt, backend/src/test/kotlin/com/etchedjournal/etched/TestUtils.kt, backend/src/test/kotlin/com/etchedjournal/etched/security/CognitoAuthenticationFilterWebTest.kt
=> GH-133 Upgraded kotlin version

frontend-ng/src/app/etches/journals/create-journal/create-journal.component.spec.ts, frontend-ng/src/app/etches/journals/create-journal/create-journal.component.ts, frontend-ng/src/app/etches/journals/journal-list-item/journal-list-item.component.html, frontend-ng/src/app/etches/journals/journal-list-item/journal-list-item.component.spec.ts, frontend-ng/src/app/etches/journals/journal-list-item/journal-list-item.component.ts, frontend-ng/src/app/etches/journals/journal-list/journal-list.component.html, frontend-ng/src/app/etches/journals/journal-list/journal-list.component.spec.ts, frontend-ng/src/app/etches/journals/journal-list/journal-list.component.ts, frontend-ng/src/app/etches/journals/journals-container/journals-container.component.html, frontend-ng/src/app/etches/journals/journals-container/journals-container.component.spec.ts, frontend-ng/src/app/models/journal/abstract-journal.ts, frontend-ng/src/app/models/journal/journal-v1.ts, frontend-ng/src/app/nav/nav.component.html, frontend-ng/src/app/nav/nav.component.spec.ts, frontend-ng/src/app/nav/nav.component.ts, frontend-ng/src/app/stores/journal.store.spec.ts, frontend-ng/src/app/stores/journal.store.ts
=> GH-109 Created schema for entry blob

backend/src/main/kotlin/com/etchedjournal/etched/controller/EntryServiceController.kt, backend/src/main/kotlin/com/etchedjournal/etched/repository/EntryRepository.kt, backend/src/main/kotlin/com/etchedjournal/etched/service/EntryService.kt, backend/src/main/kotlin/com/etchedjournal/etched/service/dto/UpdateEntryReq.kt, backend/src/main/kotlin/com/etchedjournal/etched/service/impl/EntryServiceImpl.kt, backend/src/test/kotlin/com/etchedjournal/etched/TestRepoUtils.kt, backend/src/test/kotlin/com/etchedjournal/etched/controller/EntryServiceControllerTests.kt, backend/src/test/kotlin/com/etchedjournal/etched/controller/EtchServiceControllerTests.kt, backend/src/test/kotlin/com/etchedjournal/etched/repository/EntryRepositoryIntegrationTest.kt, backend/src/test/kotlin/com/etchedjournal/etched/repository/EtchRepositoryIntegrationTest.kt, backend/src/test/kotlin/com/etchedjournal/etched/service/impl/EntryServiceImplIntegrationTest.kt, frontend-ng/src/app/etches/editor/editor-container-utils.spec.ts, frontend-ng/src/app/etches/editor/editor-container-utils.ts, frontend-ng/src/app/etches/editor/editor-container.component.ts, frontend-ng/src/app/etches/editor/existing-entry-editor-container/existing-entry-editor-container.component.spec.ts, frontend-ng/src/app/etches/editor/existing-entry-editor-container/existing-entry-editor-container.component.ts, frontend-ng/src/app/etches/entry-list/entry-list-container.component.spec.ts, frontend-ng/src/app/etches/entry-list/entry-list-container.component.ts, frontend-ng/src/app/etches/entry-list/entry-list-item/entry-list-item.component.spec.ts, frontend-ng/src/app/etches/entry-list/entry-list-item/entry-list-item.component.ts, frontend-ng/src/app/etches/entry-list/entry-list/entry-list.component.spec.ts, frontend-ng/src/app/etches/entry-list/entry-list/entry-list.component.ts, frontend-ng/src/app/models/entry/abstract-entry.ts, frontend-ng/src/app/models/entry/entry-v1.ts, frontend-ng/src/app/services/entry.service.spec.ts, frontend-ng/src/app/services/entry.service.ts, frontend-ng/src/app/stores/entry.store.spec.ts, frontend-ng/src/app/stores/entry.store.ts
=> GH-108 Can edit entry titles

frontend-ng/src/app/app.component.spec.ts, frontend-ng/src/app/app.component.ts, frontend-ng/src/app/stores/etch/etch-queue.spec.ts, frontend-ng/src/app/stores/etch/etch-queue.ts
=> GH-44 Preventing navigating away when etches are not yet saved

frontend-ng/src/app/utils/editable-text/editable-text.component.spec.ts, frontend-ng/src/app/utils/editable-text/editable-text.component.ts, frontend-ng/src/app/utils/test-utils.spec.ts
=> Fix editable text component
